### PR TITLE
Add a matches method to make it possible to write your own unapply

### PR DESCRIPTION
**Pull request by hamnis**

### CODE REVIEW

**Comment by oyvindberg** [comment]
Slightly negative, unless there is something I'm not seeing?
Exposing `unapply` guides users towards matching and extracting in one step, as opposed to more brittle `Boolean` logic. And you can already write custom extractors outside of linx if you wanted to?

That said feel free to go ahead if it's useful for you :)

**Comment by hamnis** [comment]
Sometimes it is useful to just know a linx matched without having to do extraction. If you for instance have just a `Linx[_, _]` type.
If there is a way to get that without casting, then I'm all ears.

an example using http4s-directives:

```scala
type WebDirective[F[+_]] = no.scalabin.http4s.directives.Directive[F, org.http4s.Response[F], org.http4s.Response[F]]
trait Route[F[+_]] {
  def path: Linx[_, _]
  def method: org.http4s.Method
  def directive: WebDirective[F]
 }
```
Unless we add types to Linx here then it becomes a bit unwieldy to use.

**Comment by hamnis** [comment]
The problem becomes apparent when you have mixes of `StaticLinx` and `VariableLinx` in for instance a `List[Route[F]]`

**Comment by oyvindberg** [comment]
Fair enough, @jteigen seemed to agree that this is useful also so go ahead

**Pull request merged**
