### PR TITLE
Expand to URI.

### PR DESCRIPTION
**Pull request by hamnis**
Maybe this needs to be in jvm, and perhaps as an implicit class.

### CODE REVIEW

**Comment by oyvindberg** [comment]
Not exactly what i had in mind when we discussed it, although this could be useful too. Is `URI` the correct class to use if the value is a template, not a valid URI?

What i had in mind was more something like this:

```scala
  class VarOps[A, X](l:Linx[A, Option[X]]){
    def apply(a:A) = l.links(a).head
    def asUri(base: URI, a: A): URI = ... // or perhaps an overload of apply?
}
 class NoVarOps[X](l:Linx[Unit, X]){
    def apply() = l.links(()).head
    def asUri(base: URI): URI = 
}
```

**Comment by hamnis** [comment]
URI is not the correct type to use when this is a template, which is why there is a total function.

**Comment by hamnis** [comment]
The API is of course up for debate.

**Comment by oyvindberg** [comment]
Right, what i dont like is the `String => String` parameter. I seem to remember you use it for `Map`s, but the signature is easily misunderstood. 

How about providing an `A`, and use `apply` to render the `Linx[A, X]` as a `String` and use that to build up the `URI`? Compiler-checked, and future-proof if/when we introduce the typed API.

**Pull request merged**
